pipeline {
  agent any
  stages {
  
    stage('Debug') {

     steps {

       sh 'pwd'
       sh 'ls -la'
       sh 'find . -name "*.java"'

     }
    }
   stage('Compile') {

 steps {

   sh 'javac multi-stage-multi-agent/hello.java'

 }

}

stage('Run') {

 steps {

   sh 'java -cp multi-stage-multi-agent hello'

 }

}
  }
}
