pipeline {
  agent none
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Compile') {
      steps {
        sh 'javac hello.java'
      }
    }
    stage('Run') {
      steps {
        sh 'java hello.java'
      }
    }
  }
}
