pipeline {
  agent any
  stages {
  
    stage('Debug') {

     steps {

       sh 'pwd'
       sh 'ls -la'
       sh 'find . -name "*.java"'

     }
    }
    stage('Compile') {
      steps {
        sh 'javac hello.java'
      }
    }
    stage('Run') {
      steps {
        sh 'java hello'
      }
    }
  }
}
